# Generated by Django 2.2.13 on 2021-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_place', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('image', models.FileField(default='', upload_to='')),
                ('slug', models.SlugField(blank=True, default='')),
                ('date', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PopularPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_place', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('image', models.FileField(default='', upload_to='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('slug', models.SlugField(blank=True, default='')),
                ('date', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RecentTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_place', models.CharField(max_length=200)),
                ('image', models.FileField(default='', upload_to='')),
                ('slug', models.SlugField(blank=True, default='')),
                ('date', models.DateTimeField(default='')),
            ],
        ),
    ]
