# Generated by Django 2.2.13 on 2021-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
