# Generated by Django 2.2.13 on 2021-01-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210107_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
